### ISSUE TITLE
Prompt.Input<string> throws InvalidCastException when used with Validators.RegularExpression

### ISSUE THREAD

**Issue by kimsey0** [shibayan/Sharprompt#156]
Creating a new, empty console project with the following code:
```csharp
var letter = Prompt.Input<string>("Please enter a lowercase letter", new[] { Validators.RegularExpression("[a-z]?") });
Console.WriteLine(letter);
```

throws an exception when run:
```
❯ dotnet run
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Func`2[System.Object,System.ComponentModel.DataAnnotations.ValidationResult][]' to type 'System.String'.
   at Sharprompt.Internal.Optional`1.Create(Object value)
   at Sharprompt.Forms.InputForm`1..ctor(InputOptions options)
   at Sharprompt.Prompt.Input[T](InputOptions options)
   at GuidValidation.Program.Main(String[] args) in C:\Projects\GuidValidation\Program.cs:line 10
```

Is this validator supposed to be used with a different `Prompt.Input` type parameter?

**Comment by shibayan** [comment]
Note the default arguments. It must be specified in `validators`.

```csharp
var letter = Prompt.Input<string>("Please enter a lowercase letter", validators: new[] { Validators.RegularExpression("^[a-z]?$") });
Console.WriteLine(letter);
```

**Comment by kimsey0** [comment]
Ah! Thank you!
