### ISSUE TITLE
Check Console.IsOutputRedirected before setting window related properties

### ISSUE THREAD

**Issue by IbexPeak** [shibayan/Sharprompt#216]
Hi shibayan,

Thanks for your great work, and your effort to keep the library on that level it is. I recently have discovered that you don't check [Console.IsOutputRedirected](https://docs.microsoft.com/de-de/dotnet/api/system.console.isoutputredirected?view=netframework-4.8)/[IsInputRedirected](https://docs.microsoft.com/de-de/dotnet/api/system.console.isinputredirected?view=netframework-4.8) when you set e.g. console cursor position or buffer size. This is not a problem in most cases, but it is when you call a console application within another application (process.Start) and redirecting the output/input. In this case, it crashes with an IOException:

```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.SetBufferSize(Int32 width, Int32 height)
   at System.Console.set_BufferWidth(Int32 value)
```

It is explained in the following link why this happens, but in short: If the output/input is redirected, some operations will fail, that need a visible console window to be open.
https://stackoverflow.com/questions/27749674/why-does-adjusting-console-buffer-raise-invalid-handle-exception-when-redirectin

So my question is: Can you please check the IsOutputRedirected/IsInputRedirected properties before accessing console-required properties? If you need help, I can provide you a pull request with the necessary changes. Or a list of properties/methods that must be checked against the mentioned properties.

Thanks in advance!

**Comment by shibayan** [comment]
I/O redirection is already checked, but with additional exception handling.
