### ISSUE TITLE
Select with enums does not support default value

### ISSUE THREAD

**Issue by gunr2171** [shibayan/Sharprompt#96]
An error is thrown if you use an enumeration type as the generic argument **and** provide a default value for the `Prompt.Select()` method.

Program.cs
```csharp
using Sharprompt;
using System;
using System.ComponentModel.DataAnnotations;

namespace SharpromptSelectEnumBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var value = Prompt.Select<MyEnum>("Select enum value", defaultValue: MyEnum.Bar);
            Console.WriteLine($"You selected {value}");
        }
    }

    public enum MyEnum
    {
        Foo,
        Bar,
        Baz
    }
}
```

Project.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sharprompt" Version="2.1.1" />
  </ItemGroup>

</Project>
```

When executing the `Prompt.Select` method, the following exception is thrown:

<pre>
System.InvalidCastException
Unable to cast object of type 'SharpromptSelectEnumBug.MyEnum' to type 'Sharprompt.Internal.EnumValue`1[SharpromptSelectEnumBug.MyEnum]'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at Sharprompt.Internal.Selector`1.InitializeDefaults(Object defaultValue)
   at Sharprompt.Internal.Selector`1..ctor(IEnumerable`1 items, Nullable`1 pageSize, Object defaultValue, Func`2 valueSelector)
   at Sharprompt.Forms.Select`1..ctor(String message, IEnumerable`1 items, Nullable`1 pageSize, Object defaultValue, Func`2 valueSelector)
   at Sharprompt.Prompt.Select[T](String message, Nullable`1 pageSize, Nullable`1 defaultValue)
   at SharpromptSelectEnumBug.Program.Main(String[] args) in C:\.......\Program.cs:line 14
</pre>

This does work correctly for simple string-based entries. For example with this code:

```csharp
var city = Prompt.Select("Select your city", new[] { "Seattle", "London", "Tokyo" }, defaultValue: "London");
```
"London" will correctly be selected by default when showing the prompt.

**Comment by shibayan** [comment]
Thanks for the bug report. I will fix it soon.
